server:
  port: 8080

spring:
  application:
    name: apigateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1   
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1         
#    compatibility-verifier:
#      enabled: false    
#    config:
#      override-none: true        
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453


