server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**
              #filters:
               # - StripPrefix=1   
                     
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order/**
             # filters:
              #  - StripPrefix=1
                
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payment/**
              #filters:
               # - StripPrefix=1   
             
#    compatibility-verifier:
#      enabled: false    
#    config:
#      override-none: true        
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453


