spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/user-db
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.H2Dialect
        
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      override-none: true    
         


  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453

  

custom:
 msg: for my thrid message  
 
payment:
  service.url : http://localhost:8081/ 
  
  
server:
 port: 8083
 #address: 0.0.0.0

